# syntax=docker/dockerfile:1

# JDK 8 image

ARG BASE_IMAGE="bellsoft/alpaquita-linux-base:stream-musl"
FROM "$BASE_IMAGE"

# jre, jdk
ARG BUNDLE_TYPE="jre"
# Whether to install Class Data Sharing archives
ARG CDS="no"
# Whether to remove APK tools from the image
ARG REMOVE_APK_TOOLS="no"

ARG MAINTAINER=""
ARG DESCRIPTION=""

LABEL maintainer="$MAINTAINER"
LABEL org.opencontainers.image.authors="$MAINTAINER"
LABEL org.opencontainers.image.description="$DESCRIPTION"

ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en
ENV JAVA_HOME="/usr/lib/jvm/liberica8"

RUN \
    set -e; command set -o pipefail; \
    case "$BUNDLE_TYPE" in \
        jre|jdk) ;; \
        *) \
            echo -n "Invalid BUNDLE_TYPE: '${BUNDLE_TYPE}'. "; \
            echo "Only 'jre' and 'jdk' are supported."; \
            exit 1; \
            ;; \
    esac; \
    case "$CDS" in \
        yes|no) ;; \
        *) \
            echo "Invalid CDS: '${CDS}'. "; \
            echo "Only 'yes' and 'no' are supported."; \
            exit 1; \
            ;; \
    esac; \
    case "$REMOVE_APK_TOOLS" in \
        yes|no) ;; \
        *) \
            echo "Invalid REMOVE_APK_TOOLS: '${REMOVE_APK_TOOLS}'. "; \
            echo "Only 'yes' and 'no' are supported."; \
            exit 1; \
            ;; \
    esac; \
    apk add --no-cache "liberica8-${BUNDLE_TYPE}-no-deps"; \
    if [ "$CDS" = "yes" ]; then \
        java -Xshare:dump; \
    fi; \
    if [ "$REMOVE_APK_TOOLS" = "yes" ]; then \
        apk del --no-cache apk-tools; \
    fi
